local opt = vim.opt

opt.cursorline = true
opt.relativenumber = true
opt.number = true
opt.numberwidth = 4
opt.mouse = "a"
opt.tabstop = 4
opt.shiftwidth = 4
opt.expandtab = true
opt.cursorline = true
opt.showmode = false
opt.hlsearch = false
opt.ignorecase = true
opt.backup = false
opt.clipboard = "unnamedplus"
opt.fileencoding = "utf-8"
opt.splitbelow = true
opt.splitright = true
opt.signcolumn = "yes"
opt.wrap = false
opt.linebreak = true
opt.scrolloff = 10
opt.sidescrolloff = 8
opt.pumheight = 10
opt.swapfile = false
opt.termguicolors = true
opt.timeoutlen = 300
